### ISSUE TITLE
Prisma schema suggestions

### ISSUE THREAD

**Issue by 2color** [aydrian/roacher-bowl-squares#1]
### User model

https://github.com/aydrian/roacher-bowl-squares/blob/ba39540144b09f7d4ee776599acb2391713905db/prisma/schema.prisma#L40-L50

- I think the `passwordMash` field has a typo and should probably be `passwordHash`
- For the `updatedAt` column, you can use the `@updatedAt` attribute instead of `@default(now())` and Prisma will automatically handle updating it on change operations 

### Game model
https://github.com/aydrian/roacher-bowl-squares/blob/ba39540144b09f7d4ee776599acb2391713905db/prisma/schema.prisma#L24-L38

- I would move the `hostId` foreign key to be next to the `host` field. That's just a readability convention.

**Comment by aydrian** [comment]
Thank you. Fixed both of these.

**Comment by 2color** [comment]
Awesome! I just updated the original issue description with a small suggestion for the Game model :)

**Comment by aydrian** [comment]
Just saw it. Also included.
